spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/curso_forum?serverTimezone=UTC
    username: zup
    password: zup
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update

